#!/bin/bash

cd /var/www/
exec >> log/minutely.log 2>&1

bin/sxc getinfo > etc/sxc.info 2>&1

# this could be moved to the "onblock" callback from the dameon... but whatever for now

# simple status file shows current success codes for all minutely jobs 
echo time:`date +%s` > etc/sxc.status.new
avail=`df . | perl -ne 'print $1 if /\S+\s+\d+\s+\S+\s+(\d+)/'`

echo "avail:$avail" >> etc/sxc.status.new

bin/forward && echo forward:1 >> etc/sxc.status.new              # forward transactions, add to db
bin/callback && echo callback:1 >> etc/sxc.status.new            # hit some urls
bin/loadlog && echo loadlog:1 >> etc/sxc.status.new              # in case db was down, load from log
bin/repair && echo repair:1 >> etc/sxc.status.new                # in case log didn't work, use the blockchain
mv -f etc/sxc.status.new etc/sxc.status

